### ISSUE TITLE
Error upon upload

### ISSUE THREAD

**Issue by AutomationMan808** [JPLeRouzic/Coralie#1]
Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in blah/gardeningblog/model/misc_functions.php on line 50

It was worth a try thank you for all your hard work

**Comment by oleteacher** [comment]
Parse error issue caused by using PHP 7+. Looks like you need PHP 8.1.

Since 7.4 is no longer being updated/supported, it will become a security issue and you may want to look into upgrading.

**Comment by JPLeRouzic** [comment]
Thanks Susan, you are absolutely right. 
Coralie needs PHP8.1 as it uses several PHP8.1 features like type hints.
I think I can close this issue @AutomationMan808 ?

**Comment by AutomationMan808** [comment]
Yes please. Sorry I didn't realize there was no backward compatibility. I still have some scripts that break on 8

Rick
