### ISSUE TITLE
This Project end?

### ISSUE THREAD

**Issue by Iquaridys** [JPLeRouzic/Coralie#2]
Because https://csrf.4lima.de/News not live

**Comment by JPLeRouzic** [comment]
Coralie's project only intended to show a direction for messy HTMLy code.
During the last 6 months, it did not rise much interest among developers, and at the same time, I slowly came to the conclusion that **HTMLy is slowly dying** for multiple reasons.

Also, Coralie could be faster as all code is included in every request, this behavior is inherited from HTMLy. A better way would be to include only the needed code, but this is a lot of work.

Also, I did develop but did not publish the code of a different version of Coralie where the UI presentation on user's browser is done in a very different way. Basically, this means that UI is separated from the backend, whereas in Coralie (and HTMLy) the UI is built bits by bits and pushed as a single unit to the browser.

You can see this new way to present UI in https://padiracinnovation.org/News/

**Comment by Iquaridys** [comment]
i love your work, thanks for bringing this to us.

I'm also interested in the different versions of Coralie

**Comment by JPLeRouzic** [comment]
Thanks for the nice comments!
